import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "1": "اهلا بعودتك,\n تسجيل الدخول!",
      "2": "ادخل البريد الالكتروني",
      "3": "البريد الالكتروني",
      "4": "ادخل كلمة السر",
      "5": "كلمة السر",

      "6": "هل نسيت كلمة السر؟",
      "7": "تسجيل الدخول ",
      "8": "لا تملك حساب ,",
      "9": "انشاء حساب ",
      "10": "ادخل اسمك",
      "11": "اسم المستخدم",
      "12": "ادخل رقم الهاتف",
      "13": "رقم الهاتف",
      "14": "تملك حساب بالفعل؟",
      "15": "فارغ!",
      "16": "اسم المستخدم غير مصرح به",
      "17": "رقم هاتف غير صحيح",
      "18": "لايمكن ان يكون اقل من",
      "19": "لا يمكن ان يكون اكبر من",
      "20": "تاكيد كلمة السر ",
      '21': "ادخل تاكيد كلمة السر",
      // ✅ إضافات من LoginController
      "dialog_success_title": "✅ مرحبًا",
      'email or password cannot be found': "الحساب او كلمة السر غير صحيحة ",
      "dialog_success_message": "تم تسجيل الدخول بنجاح.",
      "dialog_error_title": "❌ خطأ",
      "dialog_unexpected_title": "⚠️ غير متوقع",
      "dialog_unexpected_code": "رمز الاستجابة:",
      "dialog_exception_title": "❌ استثناء",
      "dialog_exception_message": "حدث خطأ غير متوقع:",
      "dialog_confirm": "موافق",
      "signup_password_mismatch": "كلمة المرور غير متطابقة",
      "signup_created_success":
          "تم إنشاء الحساب بنجاح، تحقق من بريدك الإلكتروني.",
      "signup_exists": "موجود مسبقًا",
      "otp_verified_title": "✅ تم التحقق",
      "otp_verified_message":
          "تم التحقق من المستخدم بنجاح، يمكنك الآن تسجيل الدخول.",
      "newpass_change_title": "✅ تم التغيير",
      "newpass_change_message": "تم تغيير كلمة المرور بنجاح",
      "newpass_unexpected_message": "رمز الاستجابة: @code",
      "forget_sent_title": "✅ تم الإرسال",
      "forget_sent_message": "تم إرسال رمز التحقق إلى بريدك الإلكتروني",
      "forget_not_found_title": "❌ غير موجود",
      "forget_error_message": "@message",
      "forget_exception_title": "❌ خطأ",
      "password_mismatch": "كلمة المرور غير متطابقة",
      "dialog_success_create": "تم انشاء الحساب ,الرجاء تسجيل الدخول الان ",
      "password not confirmation": "كلمة السر غير متطابقة ",
      "email is exists ready": "الحساب موجود مسبقا ",
      "phone is exists ready": "رقم الهاتف موجود مسبقا ",
      "phone and email is exists ready": "الحساب و رقم الهاتف موجود مسبقا ",
      "phone format invaild": "خطا في تنسيق رقم الهاتف",
    },
    "en": {
      "1": "Welcome Back, \n Login!",
      "2": "Enter your Email",
      "3": "Email",
      "4": "Enter your Password",
      "5": "Password",
      "6": "Forget your Password?",
      "7": "Login",
      "8": "you not have Account,",
      "9": "SignUp",
      "10": "Enter your UserName",
      "11": "UserName",
      "12": "Enter Your Phone ",
      "13": "Phone",
      "14": "have account ready? ",
      "15": "Empty! ",
      "16": "valid username",
      "17": "valid is number",
      "18": "can not be less",
      "19": "can not be larger",
      "20": "confirm password",
      '21': "Enter Confirm Password",
      // ✅ إضافات من LoginController
      "dialog_success_title": "✅ Welcome",
      "email or password cannot be found": "email or password cannot be found",
      "dialog_success_message": "Login successful.",
      "dialog_error_title": "❌ Error",
      "dialog_unexpected_title": "⚠️ Unexpected",
      "dialog_unexpected_code": "Response code:",
      "dialog_exception_title": "❌ Exception",
      "dialog_exception_message": "An unexpected error occurred:",
      "dialog_confirm": "OK",
      "signup_password_mismatch": "Password do not match",
      "signup_created_success":
          "Account created successfully, check your email.",
      "signup_exists": "Already exists",
      "otp_verified_title": "✅ Verified",
      "otp_verified_message": "User verified successfully, you can login now.",
      "newpass_change_title": "✅ Changed",
      "newpass_change_message": "Password changed successfully",
      "newpass_unexpected_message": "Response code: @code",
      "forget_sent_title": "✅ Sent",
      "forget_sent_message": "A verification code has been sent to your email",
      "forget_not_found_title": "❌ Not found",
      "forget_error_message": "@message",

      "password_mismatch": "Passwords do not match",
      "dialog_success_create": "register succsess ,please login now ",
      "password not confirmation": "The password confirmation does not match.",
      "email is exists ready": 'email is exists ready',
      "phone is exists ready": "phone is exists ready",
      "phone and email is exists ready": "phone and email is exists ready",
      "phone format invaild": "phone format invaild",
    },
  };
}
